### ISSUE TITLE
rating_system: populate prefilled data on rating page after navigating from dashboard

### ISSUE THREAD

**Issue by jadatwo** [addie-p/Team20-Project#115]
Point Value: 2
Size Category: Small
Description: On dashboard.html, when the user clicks the arrow to review a restaurant, change the text box allowing the user to type in the restaurant to an already populated box of the restaurant chosen. Also, keep the review there so that the user can find their past review instead of clearing the data after submission. This dummy proofs the data that allows the server to save the data correctly

**Comment by addie-p** [comment]
Awesome job Jada - the data is definitely dummy-proofed, tested it on my end. Going back to the review also works for me!
