### ISSUE TITLE
photo upload feature: post and get images for restaurant reviews

### ISSUE THREAD

**Issue by helenliuf** [addie-p/Team20-Project#117]
use express and multer to post and get images to an endpoint, maybe not an endpoint when tested further

Point Value: 4 points
Size Category: Medium
Description: Create a table in SQLite database for images, saving images with their file and restaurant name. IndexedDB maintained for persistent data. Set up POST /upload and GET /image/:restaurant_name to upload and retrieve images from back-end.

**Comment by helenliuf** [comment]
works with own server file but need to integrate with project's overall server.js backend file

**Comment by helenliuf** [comment]
image can be uploaded with the /upload route with image (file) parameter and restaurant name parameter, and can also be retrieved with file name at /image3/:filename and restaurant name at /image/:restaurant_name endpoint from localhost:{port}

**Comment by evc29** [comment]
Great job Helen, I can see the endpoints for your photo upload feature are working properly!

**Comment by cding888** [comment]
Great work. Your photo upload feature is working well with SQLite!

**Comment by jadatwo** [comment]
Photos properly upload, nice! Will need to dummy-proof restaurant name textbox so the application prefills the name instead of allowing the user to input the name of the restaurant.
