### ISSUE TITLE
Implement Restaurants Database

### ISSUE THREAD

**Issue by addie-p** [addie-p/Team20-Project#120]
**Point Value:** 2 points
**Size Category:** Small
**Description:** Dynamically load CSV data into the backend using script to read/parse file; convert rows into JS objects matching db schema. Connect to an SQLite database, clear existing data, and insert parsed rows to store data in the Restaurant table for use in the restaurant cards and other features.

**Comment by addie-p** [comment]
Script created to parse CSV and insert into SQLite.

**Comment by evc29** [comment]
Connected to SQLite database and everything looks good!

**Comment by helenliuf** [comment]
Server.js working and running and can load restaurants with SQLite database!

**Comment by cding888** [comment]
Server.js is running with SQLite database, good work!
