### ISSUE TITLE
rating system feature: create review model, set up routes, add Sequelize

### ISSUE THREAD

**Issue by jadatwo** [addie-p/Team20-Project#124]
Point Value: 4
Size Category: Medium
Description: For m4, incorporate backend architecture to create a review model and set up routes for creating, updating, and retrieving reviews. Add Sequelize associations between User, Restaurant, and Review. Retrieve data from dashboard's backend to populate the prefilled data. Store data in backend.

**Comment by cding888** [comment]
Beautifully done, Jada! It's great to see that reviews are stored in the backend, and that data can be retrieved from the backend too!

**Comment by addie-p** [comment]
Nice job Jada! The CRUD operations work as intended and this subissue is ready to be closed out
