### ISSUE TITLE
[FEATURE] Saved Restaurants Management Feature

### ISSUE THREAD

**Issue by evc29** [addie-p/Team20-Project#125]
Point Value: 6

Size Category: Large

Description: This feature includes building CRUD operations for managing the saved restaurants dashboard. This feature includes adding endpoints for adding, retrieving, updating, and deleting saved restaurants. This will connect with SQLite to obtain saved restaurant data to display, changing how the dashboard currently works with IndexedDB to create a working application with a functional backend. This works by fetching data from the Liked Restaurants table in the back-end and pushing changes to both the Liked Restaurants and the Visited Restaurants table which I created in this feature. 

Decision: Will be included and I (Eva) implemented it and no necessary adjustments

Sub-Issues:
#159: Create Visited Restaurants Table in the Back-end
#161: Connecting Visited Restaurants Table and Liked Restaurants Table to re-write Saved Restaurants Dashboard

**Comment by evc29** [comment]
Closed with @evc29
[Saved Dashboard Feature (](https://github.com/addie-p/Team20-Project/commit/b1fd4ca212a3df32887481701b5e7488601298a1)https://github.com/addie-p/Team20-Project/issues/125[)](https://github.com/addie-p/Team20-Project/commit/b1fd4ca212a3df32887481701b5e7488601298a1) commit in m4_saved_dashboard branch

**Comment by evc29** [comment]
Closed with @evc29
[Saved Dashboard Feature (](https://github.com/addie-p/Team20-Project/commit/b1fd4ca212a3df32887481701b5e7488601298a1)https://github.com/addie-p/Team20-Project/issues/125%5B)%5D(https://github.com/addie-p/Team20-Project/commit/b1fd4ca212a3df32887481701b5e7488601298a1) commit in m4_saved_dashboard branch

**Comment by cding888** [comment]
Nice work Eva! Feature works well with the SQLite database, and restaurant is saved appropriately!

**Comment by addie-p** [comment]
Great job Eva, this issue looks good for your assigned feature! It is important to implement a table in the backend for restaurants that are visited so that there is modular organization in the backend and so a single table is not being crowded with unnecessary information. The usage and connection between the Liked Restaurants and Visited Restaurants table will work well.

**Comment by SandraV255** [comment]
Hi Eva, great work on integrating your feature with the backend of our application!! The tables for Visited and Liked restaurants in the database are a great way to organize the saved restaurants in the SQLite database.
