### ISSUE TITLE
[FEATURE] Geolocation and Filter

### ISSUE THREAD

**Issue by SandraV255** [addie-p/Team20-Project#126]
Description:
We are adding a dropdown bar giving the user the option to choose where they are located from 4 towns: Northampton, Amherst, Hadley, and South Hadley. We then pull the latitude and longitude coordinates of each restaurant from the SQLite database to calculate the distance between the location chosen by the user (we use coordinates in the center of each town) and the restaurant. We connect this to the filter feature so that the user can filter the restaurants by maximum distance from their chosen location. We also update the Cuisine, Vegetarian, and Price Range filters so that they accurately filter the restaurants when the data is being pulled from the database. Additionally, the mini-map is updated to zoom in on the location selected by the user and display the filtered restaurants by pulling the coordinates from the filtered restaurants array.

Point Value: 6 Points

Size Category: Large

Owner: Aliya and Sandra

Corresponding Sub-Issues: 
(#145): Creating the mini map to pull data from the database
(#154): Fixing cuisine, vegetarian, and price range filters 
(#181): Updating filter system to integrate with backend
(#166):  Fixing the mini-map with the location dropdown in the filter system + Showing the restaurant markers from the database

Edits: 
(#167): Fixing price dropdown to display $ signs instead of numbers and fixing max distance for non-integer inputs 
(#184) Updating geolocation to work with integrate_name

**Comment by addie-p** [comment]
This issue looks good to be assigned, Aliya and Sandra! It will take some work to implement the filter feature with the pre-existing server-side implementation and populate the map according to the location that the user selects. I think it's a great idea to collaborate on this feature to include a geolocation component within the filter itself to narrow down restaurants in each area. Great!

**Comment by addie-p** [comment]
This issue looks good to be assigned, Aliya and Sandra! It will take some work to implement the filter feature with the pre-existing server-side implementation and populate the map according to the location that the user selects. I think it's a great idea to collaborate on this feature to include a geolocation component within the filter itself to narrow down restaurants in each area. Great!

**Comment by cding888** [comment]
Good work guys! This will be an important feature on our website after it is completed!

**Comment by helenliuf** [comment]
I like the idea of having users choose where they're located, still gives users the option of customization without pinpointing where the user's specific location, making it more feasible to complete for M4 but also still a complex feature. The filtering system in general is also important to bring down the amount of restaurants shown to users, so having it work correctly would be a good thing to work on for this milestone!

**Comment by evc29** [comment]
Good job guys! This is a very important feature for our website's functionality. Giving the option for the user to choose where their located gives more room for options which is important and they wont have to give their exact address, saving their privacy. Having this work would be a great thing for our milestone!
