### ISSUE TITLE
Implement Registering feature 

### ISSUE THREAD

**Issue by cding888** [addie-p/Team20-Project#132]
Allow users to register for Plateful by entering a username and password. Save this username and password to SQLite

**Comment by evc29** [comment]
Beautifully done Carol, works seamlessly.

**Comment by cding888** [comment]
Point Value: 2 points
Size category: small
Description: The registration feature enables new users to create an account for the web application. It provides an interactive registration form on the frontend that collects user details, including a username,and password. Upon submission, the form sends a POST request to the /auth/register API endpoint.The backend handles registration by validating input data, securely hashing passwords using bcrypt.js, and saving user information to the database. Errors, such as duplicate usernames or invalid input, are communicated back to the frontend for user feedback. Once successfully registered, users are redirected to the login page to access their account.
