### ISSUE TITLE
Implement Login feature

### ISSUE THREAD

**Issue by cding888** [addie-p/Team20-Project#133]
Allow users to login to Plateful using the username and password that they registered with. If a username or password entered is incorrect, return an error.

**Comment by evc29** [comment]
Beautifully done, Carol! Works well.

**Comment by cding888** [comment]
Point Value: 2 points
Size Category: Small
Description: The login feature allows existing users to securely access their accounts. The frontend provides an interactive login form where users input their username and password. Upon submission, the form sends a POST request to the /auth/login API endpoint.The backend processes the login request using Passport.js with Local Strategy to validate the provided credentials against stored user data. A successful login establishes a persistent session using express-session, allowing users to access personalized features. If the login fails due to incorrect credentials or other errors, appropriate feedback is displayed on the frontend. After a successful login, users are redirected to the home page to begin the search for their ideal restaurant.
