### ISSUE TITLE
Connect login page to rest of website 

### ISSUE THREAD

**Issue by cding888** [addie-p/Team20-Project#135]
After the user succesfully logs in, the page should switch to the main page of Dashboard where the user an then start finding their ideal restaurant.

**Comment by cding888** [comment]
all fixed!

**Comment by addie-p** [comment]
Frontend implement in conjunction with server-side implementation. Tested and functional - merge request to integration branch made. Looks good!

**Comment by jadatwo** [comment]
Tested and works to create and save user login and password. Will need to make register/login the landing page

**Comment by cding888** [comment]
Point Value: 2 points
Size Category: Small
Description: The feature connects the login page to the rest of the website, enabling authenticated navigation and user-specific access. Upon successful login, the application redirects users from the login page to the home page, granting access to features like saved and visited restaurants.The frontend dynamically updates the navigation bar to reflect the user's logged-in status, displaying options such as a logout button.The backend ensures session persistence with express-session, allowing users to remain authenticated as they navigate between pages. Protected routes across the site use authentication middleware to prevent unauthorized access, redirecting users to the login page if they are not authenticated. This ensures secure and personalized user experiences throughout the application.
