### ISSUE TITLE
Render Restaurants From Database

### ISSUE THREAD

**Issue by addie-p** [addie-p/Team20-Project#138]
**Point Value:** 1 point
**Size Category:** Small
**Description:** Use stored data in database to render restaurant cards instead of the Restaurants.csv file; make POST request to database in the card swipe listener function to render the next restaurant card from db on click (like/dislike).

**Comment by addie-p** [comment]
Restaurants are correctly rendered (and all their respective fields) with information that is dynamically populated from a Restaurants table in the database.

**Comment by evc29** [comment]
Restaurants are rendered correctly! Good job addie!
