### ISSUE TITLE
[FEATURE] Login & Authentication

### ISSUE THREAD

**Issue by addie-p** [addie-p/Team20-Project#158]
Description:
We are implementing the login and authentication system for our web application, which securely manages user accounts, enabling personalized access to saved and visited restaurants. The frontend includes interactive forms (for registering an account and logging in) that send POST requests to the database. Successful logins redirect users to the home page, while a logout button in the navigation bar terminates sessions. 

Key API routes include /auth/register for user registration, /auth/login for authentication, and /auth/logout for session termination. CORS policies ensure secure requests from trusted origins. Sensitive endpoints are protected with authentication middleware.

Point Value: 6 Points

Size Category: Large

Owner: Addie and Carol

Corresponding Sub-Issues:
#132: Implement registering feature
#133: Implement log-in feature
#135: Connect log-in page to the rest of the website

Bug Fixes:
#172: Protected Routes for Login

**Comment by addie-p** [comment]
The register/login feature is completely implemented; each subissue has been closed out after implementation and the authentication has been tested locally on each of our computers to ensure functionality.

**Comment by addie-p** [comment]
Reopening to address security bug in authentication process.

**Comment by addie-p** [comment]
Closing this issue as the bug fix has been resolved (see #172) and code was successfully merged upon approval from reviewers.

**Comment by helenliuf** [comment]
Nice feature to work on and make the app more reliable to users, creating important routes for basic authentication.

**Comment by SandraV255** [comment]
Login and authentication feature works very well, great job Addie and Carol! The pages correctly send POST requests to the back end and allow users to register and login successfully.
