### ISSUE TITLE
Create Visited Restaurants Table in Back-end

### ISSUE THREAD

**Issue by evc29** [addie-p/Team20-Project#159]
Point Value: 3
Size Category: Medium
Description: Create the Visited Restaurants Table in the Back-End with working CRUD operations to be pulled and pushed in the Saved Dashboards Feature. This Visited Restaurants Table which will be implemented in this issue will be used in Issue #161 to connect the tables. 

Connects to Larger Feature: #125

**Comment by addie-p** [comment]
CRUD operations work as intended - the Visited restaurants table are being updated as a user "visits" them on the dashboard. Nice job!
