### ISSUE TITLE
[FEATURE] Rating System Feature: Implement M4 backend 

### ISSUE THREAD

**Issue by jadatwo** [addie-p/Team20-Project#160]
Description:
Connect rating system to the backend to retrieve and store data to accurately save corresponding reviews. The frontend includes interactive input forms and stems from the dashboard page so it's independent for each restaurant. It connects to the photo uploads page so that the user can upload photos and it can appear on the rating page when a user wants to come back and see what they have inputted in the past. 

Point Value: 5 Points

Size Category: Large

Owner: Jada

Corresponding Sub-Issues:
#115 
#124

**Comment by addie-p** [comment]
This feature looks good! We definitely need to connect each component to the backend through database integration so using a backend connection for reviews and connecting to the photo upload feature is necessary. Looks good to be assigned.

**Comment by evc29** [comment]
Looks good Jada! This component looks like it will work correctly when completed.

**Comment by jadatwo** [comment]
Feature uses backend to retrieve restaurant data successfully and stores the data so that the user can revisit their review. Must double check if it correctly connects to other components

**Comment by helenliuf** [comment]
Looks like a good feature to be implemented for M4! Good to connect to data in the backend and store user's reviews. Might still need to connect to photo uploads page/photo endpoints to retrieve the image on the review page, or the user could go to the photo uploads page and type in the restaurant name. If the photo upload page had the restaurant filled in, that could also be accessible to the user.

**Comment by SandraV255** [comment]
Great work on your rating/review system feature for this milestone Jada! Successfully pulls data from the backend and stores review data for users.
