### ISSUE TITLE
Connecting Visited Restaurants Table and Liked Restaurants Table into Saved Restaurants Dashboard

### ISSUE THREAD

**Issue by evc29** [addie-p/Team20-Project#161]
Point Value: 3
Size Category: Medium
Description: Connecting the two tables Visited Restaurants Table which was created and Liked Restaurants Table to redo my Saved Restaurants Dashboard to correctly use CRUD operations with the back-end to correctly pull the Liked Restaurants into the Liked section and correctly delete from Liked Restaurants and add to Visited Restaurants from my dashboard and vice versa. This uses POST and DELETE operations to do so. 

Connects to Larger Feature:  #125

**Comment by addie-p** [comment]
The server-side implementation of the saved restaurants dashboard looks great on my end - good job Eva!
