### ISSUE TITLE
[FEATURE] Server-Side Implementation for Restaurants

### ISSUE THREAD

**Issue by addie-p** [addie-p/Team20-Project#162]
Description: 
I am completing the server-side implementation of the restaurants feature using an SQLite database to manage restaurant data, replacing the previous CSV file setup (Restaurants.csv). We will still keep the CSV file and use a custom script to load data from the CSV file into the database by parsing rows into JavaScript objects and inserting them into the Restaurant table. 

The tables in the backend that I am implementing in this feature are the Restaurants and LikedRestaurants table, which are utilized for the rendering of the restaurant cards and for other features such as the saved restaurants dashboard. Express.js routes, models, and controllers handle database operations such as fetching, adding, and deleting restaurants
and the Server.js file will serve as the central entry point for the entire backend application. It will set up and configure the Express.js server, and connects the various backend components like routes, models, and middleware.

Point Value: 6 Points

Size Category: Large

Owner: Addie

Corresponding Sub-Issues:
#118: Set up server-side architecture
#120: Implement restaurants database using script
#127: Implement liked restaurants database and sync
#138: Render restaurants from database as cards

Bug Fixes:
#177: Updating 'Liked' Status for Restaurants Table

**Comment by addie-p** [comment]
Closing out this issue as all corresponding sub-issues have been implemented and closed. The server-side implementation is created along with the database and all corresponding tables. The restaurant cards on the home page are dynamically rendered using information from the database

**Comment by evc29** [comment]
Looks good Addie, The Server-Side Implementation looks good along with the database and tables. It seems to be rendering correct information from database into the restaurant cards too. Good job!

**Comment by addie-p** [comment]
Reopening to implement a fix for the bug documented in #177 to address the issue of not having a liked column, since this affects the filter functionality.

**Comment by addie-p** [comment]
Closing as the bug has been properly fixed, with the documentation in the corresponding bug issue documented, and the code merged after approval to the integrated branch.

**Comment by helenliuf** [comment]
This looks like good feature to implement for M4 to get more real restaurant data loaded into the app and make sure others can build off of it with the same data structure! It's correctly loading the restaurant data for the group to use and to display on the app pages. Thank you, Addie!
