### ISSUE TITLE
[FEATURE] photo uploads: Server and Client Side Saved Restaurant Photos

### ISSUE THREAD

**Issue by helenliuf** [addie-p/Team20-Project#178]
Description: Create a Sequelize images table with attributes for image files and restaurant name text inputs. Create a POST /upload route to save images in the SQLite database in the images table with the corresponding restaurant name. Create a GET /image/:restaurant_name route to retrieve an image from the images table by its matching restaurant name, given as a parameter. Connect both routes to the front-end of the photo upload page/feature, converting the user's uploaded images to send to the /upload endpoint upon submit button clicking, and converting the GET /image data back into a photo to display when the restaurant name is saved in the images table already.

Point Value: 6 points

Size Category: Large

Owner: Helen

Corresponding Sub Issues:
#117 : Set up SQLite database, the images Sequelize table, and create /upload and /image/:restaurant_name routes with SQLite3, Express.js, and Multer to save and retrieve images
#116 : Connect and use routes in front-end of the photo upload page to save user's uploaded images with a restaurant name
#150 : Migrate photo server javascript into app's primary Server.js to avoid having to run on a different port after fixing app's Server.js to function properly in #120
#175, #180 : Connect and use routes in front-end of the photo upload page and rating system to page to track restaurant input field and retrieve the image of a restaurant if an image already exists/is saved according to the text

**Comment by SandraV255** [comment]
Hi Helen, great work on your feature for milestone 4! The Sequelize table you created for images and corresponding routes connecting to the front end and SQLite database function as intended.
